# Generated by Django 5.2 on 2025-04-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('guardianphone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('studentroll', models.CharField(max_length=100)),
            ],
        ),
    ]
