# Generated by Django 5.2 on 2025-04-23 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acc_holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(blank=True, max_length=100, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseRegister',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AlterField(
            model_name='student',
            name='studentroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.acc_holder'),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
